REVOKE ALL ON ALL TABLES IN SCHEMA catalog FROM PUBLIC;
REVOKE ALL ON SCHEMA catalog FROM PUBLIC;

GRANT USAGE ON SCHEMA catalog TO chatddx_writer, chatddx_reader;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA catalog TO chatddx_writer;
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO chatddx_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT SELECT, INSERT ON TABLES TO chatddx_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog
    GRANT SELECT ON TABLES TO chatddx_reader;
